alias untar='tar -zxvf'
alias wp=~/scripts/./wallpaper.sh
# alias gvim="gvim 2>/dev/null"
alias rm="rm -i"
alias c="clear"
alias h="history"
alias lsdir="ls -d */"
alias o="gnome-open"
#alias python="python3"
